### ISSUE TITLE
How do you run it?

### ISSUE THREAD

**Issue by T0071** [CodyEngel/Amazon-Price-Tracker#1]
How do you Run the application. Can you add it to the readme.

**Comment by CodyEngel** [comment]
Hey thanks for your interest and sorry about the delay in responding. I updated the readme to give details on how to get it running minus the database schema (sorry I don't really remember all the details of it, but if you poke around you can probably reverse engineer that part).

This project was more intended to help people see how it could be done, but I never intended for it to be a super easy setup process (sorry). In the future I'll do a better job with documenting setup and hopefully include some automated  scripts to set things up.
